import copy
import json

import click
from scripts.question_reuse.config.components_to_reuse import (
    COMPONENTS_TO_REUSE,
)
from scripts.question_reuse.config.lookups import LOOKUPS
from scripts.question_reuse.config.pages_to_reuse import PAGES_TO_REUSE
from scripts.question_reuse.config.sub_pages_to_reuse import SUB_PAGES_TO_REUSE

BASIC_FORM_STRUCTURE = {
    "metadata": {},
    "startPage": None,
    "backLinkText": "Go back to application overview",
    "pages": [],
    "lists": [],
    "conditions": [],
    "fees": [],
    "sections": [],
    "outputs": [
        {
            "name": "update-form",
            "title": "Update form in application store",
            "type": "savePerPage",
            "outputConfiguration": {"savePerPageUrl": "True"},
        }
    ],
    "skipSummary": False,
    "name": "Generated by script",
}

BASIC_PAGE_STRUCTURE = {
    "path": None,
    "title": None,
    "components": [],
    "next": [],
    # "controller": None,
    "options": {},
}

SUMMARY_PAGE = next(
    page
    for page in SUB_PAGES_TO_REUSE["subpages"]
    if page["path"] == "/summary"
)


def build_page(input_page_name: str) -> dict:
    input_page = PAGES_TO_REUSE[input_page_name]
    page = copy.deepcopy(BASIC_PAGE_STRUCTURE)
    page.update(
        {
            "path": f"/{input_page_name}",
            "title": LOOKUPS[input_page_name],
        }
    )
    # Having a 'null' controller element breaks the form-json, needs to not be there if blank
    if controller := input_page.get("controller", None):
        page["controller"] = controller
    for component_name in input_page["component_names"]:
        component = copy.deepcopy(COMPONENTS_TO_REUSE[component_name])
        component["name"] = component_name
        conditions = component.get("conditions", None)
        if conditions:
            component.pop("conditions")

        page["components"].append(component)

    return page


def build_navigation(results: dict, input_pages: list[str]) -> dict:
    for i in range(0, len(input_pages)):
        if i < len(input_pages) - 1:
            next_path = input_pages[i + 1]
        elif i == len(input_pages) - 1:
            next_path = "summary"
        else:
            next_path = None
        this_path = input_pages[i]
        this_page_in_results = next(
            p for p in results["pages"] if p["path"] == f"/{this_path}"
        )
        this_page_in_results["next"].append({"path": f"/{next_path}"})

    return results


def build_form_json(input_json: dict) -> dict:

    results = copy.deepcopy(BASIC_FORM_STRUCTURE)

    start_page = copy.deepcopy(BASIC_PAGE_STRUCTURE)
    start_page.update(
        {
            "title": LOOKUPS[input_json["title"]],
            "path": f"/intro-{input_json['title']}",
            "controller": "./pages/start.js",
            "next": [{"path": f"/{input_json['pages'][0]}"}],
        }
    )

    results["pages"].append(start_page)
    results["startPage"] = start_page["path"]

    for page in input_json["pages"]:
        results["pages"].append(build_page(page))

    results = build_navigation(results, input_json["pages"])

    results["pages"].append(SUMMARY_PAGE)

    return results


@click.command()
@click.option(
    "--input_file",
    default="./scripts/question_reuse/test_data/in/org-info_basic_name_address.json",
    help="Input configuration",
    prompt=True,
)
@click.option(
    "--output_file",
    default="../digital-form-builder/runner/dist/server/forms/name_address_basic.json",
    # "./test_data/out/org-info_basic_name_address.json",
    help="Output destination",
    prompt=True,
)
def generate_form_json(input_file, output_file):
    with open(input_file, "r") as f:
        input_data = json.load(f)

    form_json = build_form_json(input_data)

    with open(output_file, "w") as f:
        json.dump(form_json, f)


if __name__ == "__main__":
    generate_form_json()
