import copy
import json

import click
from scripts.question_reuse.config.components_to_reuse import (
    COMPONENTS_TO_REUSE,
)
from scripts.question_reuse.config.lookups import LOOKUPS
from scripts.question_reuse.config.pages_to_reuse import PAGES_TO_REUSE
from scripts.question_reuse.config.sub_pages_to_reuse import SUB_PAGES_TO_REUSE

BASIC_FORM_STRUCTURE = {
    "metadata": {},
    "startPage": None,
    "backLinkText": "Go back to application overview",
    "pages": [],
    "lists": [],
    "conditions": [],
    "fees": [],
    "outputs": [
        {
            "name": "update-form",
            "title": "Update form in application store",
            "type": "savePerPage",
            "outputConfiguration": {"savePerPageUrl": "True"},
        }
    ],
    "skipSummary": False,
    "name": "Generated by script",
}

SUMMARY_PAGE = next(
    page
    for page in SUB_PAGES_TO_REUSE["subpages"]
    if page["path"] == "/summary"
)


def build_page(input_page_name: str) -> dict:
    input_page = PAGES_TO_REUSE[input_page_name]
    page = {
        "path": f"/{input_page_name}",
        "title": LOOKUPS[input_page_name],
        "components": [],
        "next": [],
        "controller": input_page.get("controller", None),
        "options": {},
    }
    for component_name in input_page["component_names"]:
        component = copy.deepcopy(COMPONENTS_TO_REUSE[component_name])
        component["name"] = component_name
        conditions = component.get("conditions", None)
        if conditions:
            component.pop("conditions")

        page["components"].append(component)

    return page


def build_form_json(input_json: dict) -> dict:

    results = copy.deepcopy(BASIC_FORM_STRUCTURE)

    start_page = {
        "title": LOOKUPS[input_json["title"]],
        "path": f"/intro-{input_json['title']}",
        "controller": "./pages/start.js",
    }

    results["pages"].append(start_page)
    results["startPage"] = start_page["path"]

    for page in input_json["pages"]:
        results["pages"].append(build_page(page))

    results["pages"].append(SUMMARY_PAGE)

    return results


@click.command()
@click.option(
    "--input_file",
    default="./test_data/in/org-info_basic_name_address.json",
    help="Input configuration",
    prompt=True,
)
@click.option(
    "--output_file",
    default="./test_data/out/org-info_basic_name_address.json",
    help="Output destination",
    prompt=True,
)
def generate_form_json(input_file, output_file):
    with open(input_file, "r") as f:
        input_data = json.load(f)

    form_json = build_form_json(input_data)

    with open(output_file, "w") as f:
        json.dump(form_json, f)


if __name__ == "__main__":
    generate_form_json()
