name: Deploy to AWS
run-name: AWS Deploy ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'Dev-Test-UAT-Prod' || 'Dev-Test') }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - dev
        - test
        - uat
        - prod
      run_performance_tests:
        required: false
        default: false
        type: boolean
        description: Run performance tests
      run_e2e_tests_assessment:
        required: false
        default: false
        type: boolean
        description: Run e2e tests (assessment)
      run_e2e_tests_application:
        required: false
        default: true
        type: boolean
        description: Run e2e tests (application)
  push:
    # Ignore README markdown and the docs folder
    # Only automatically deploy when something in the app or tests folder has changed
    paths:
      - '!**/README.md'
      - '!docs/**'
      - 'app/**'
      - 'config/**'
      - 'tests/**'
      - 'requirements-dev.in'
      - 'requirements-dev.txt'
      - 'requirements.in'
      - 'requirements.txt'
      - '.github/workflows/copilot_deploy.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      jobs_to_run: ${{ steps.determine-jobs.outputs.job_list }}
    steps:
      - id: determine-jobs
        run: |
          if [ "${{ inputs.environment }}" != '' ]; then
            export jobs='["${{ inputs.environment }}"]'
          elif [ "${{ github.ref }}" == 'refs/heads/main' ]; then
            export jobs='["dev", "test", "uat", "prod"]'
          else
            export jobs='["dev", "test"]'
          fi
          echo "job_list=$(jq -cn --argjson keys "$jobs" '$keys')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  pre_deploy_tests:
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/pre-deploy.yml@main
    with:
      postgres_unit_testing: false



  post_dev_deploy_tests:
    needs: pre_deploy_tests
    concurrency:
      group: 'fsd-preaward-dev'
      cancel-in-progress: false
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@bau-add-manual-params
    with:
      run_performance_tests: ${{ inputs.run_performance_tests || false }}
      run_e2e_tests_assessment: ${{ inputs.run_e2e_tests_assessment || false }}
      run_e2e_tests_application: ${{ inputs.run_e2e_tests_application || false }}
      app_name: frontend
      environment: dev
