name: Deploy to AWS
run-name: AWS Deploy ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'Dev-Test-UAT-Prod' || 'Dev-Test') }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - dev
        - test
        - uat
        - prod
      run_performance_tests:
        required: false
        default: false
        type: boolean
        description: Run performance tests
      run_e2e_tests_assessment:
        required: false
        default: false
        type: boolean
        description: Run e2e tests (assessment)
      run_e2e_tests_application:
        required: false
        default: true
        type: boolean
        description: Run e2e tests (application)
  push:
    # Ignore README markdown and the docs folder
    # Only automatically deploy when something in the app or tests folder has changed
    paths:
      - '!**/README.md'
      - '!docs/**'
      - 'app/**'
      - 'config/**'
      - 'tests/**'
      - 'requirements-dev.in'
      - 'requirements-dev.txt'
      - 'requirements.in'
      - 'requirements.txt'
      - '.github/workflows/copilot_deploy.yml'

jobs:
  setup:
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/determine-jobs.yml@fs-4294-shared-determine-jobs
    with:
      environment: ${{ inputs.environment }}


  test_jobs_to_run:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - id: print_jobs
        run: |
          echo Job list: ${{ needs.setup.outputs.jobs_to_run }}
