name: Deploy to Gov PaaS

on:
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - test
        - uat
      copilot:
        description: Whether to deploy to AWS?
        type: boolean
        required: false
        default: false
      deploy_to_dev:
        required: false
        default: false
        type: boolean
        description: Deploy to CloudFoundry dev?
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  test_and_deploy:
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.inputs.copilot }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/deploy.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
      api: false
      assets_required: true
      deploy_to_dev: true
      include_manifest: true
      run_performance_tests: true
      run_e2e_tests: true
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USERNAME}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
      E2E_PAT: ${{secrets.E2E_PAT}}
      RSA256_PUBLIC_KEY_BASE64: ${{secrets.RSA256_PUBLIC_KEY_BASE64}}
      SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      FORMS_SERVICE_PRIVATE_HOST: ${{secrets.FORMS_SERVICE_PRIVATE_HOST}}
  paketo_build:
    permissions:
      packages: write
    uses: ./.github/workflows/package.yml
    with:
      version_to_build: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
  pre_deploy_tests:
    if: ${{ github.event.inputs.copilot }}
    secrets:
      E2E_PAT: ${{secrets.E2E_PAT}}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/pre-deploy.yml@main
    with:
      postgres_unit_testing: false
