#name: Deploy xforms to Gov PaaS
#
#on:
#  workflow_dispatch:
#  push:
#    # branches:
#    # - master
#    # - FS-389
#    # - FS-390
#
#    paths-ignore:
#      - '**/README.md'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    environment: Dev
#    services:
#      runner:
#        image: ghcr.io/xgovformbuilder/digital-form-builder-runner:latest
#        ports:
#           - 3009:3009
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.GHCR_USER }}
#          password: ${{ secrets.GHCR_PAT }}
#
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: |
#            ghcr.io/communitiesuk/frontend-runner-${{ github.ref_name }}:latest
#            ghcr.io/communitiesuk/frontend-runner-${{ github.ref_name }}:1.0
#
#  use:
#    runs-on: ubuntu-latest
#    environment: Dev
#    needs: build
#    services:
#      runner:
#        image: ghcr.io/communitiesuk/frontend-runner-${{ github.ref_name }}:latest
#        credentials:
#          username: ${{ secrets.GHCR_USER }}
#          password: ${{ secrets.GHCR_PAT }}
#        ports:
#           - 3009:3009
#
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
