name: Deploy xforms to Gov PaaS

on:
  workflow_dispatch:
  push:
    # branches:
    # - master
    # - FS-389
    # - FS-390

    paths-ignore:
      - '**/README.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: Dev
    # container: ghcr.io/xgovformbuilder/digital-form-builder-runner:latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: grab Xforms runner
        run: docker pull ghcr.io/xgovformbuilder/digital-form-builder-runner:latest
      - name: debug list images
        run: docker images
      # - name: run docker container
      #   run: |
      #     docker ps
      #     docker run ghcr.io/xgovformbuilder/digital-form-builder-runner:latest 