name: Deploy xforms to Gov PaaS

on:
  workflow_dispatch:
  push:
    # branches:
    # - master
    # - FS-389
    # - FS-390

    paths-ignore:
      - '**/README.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: Dev
    container: ghcr.io/xgovformbuilder/digital-form-builder-runner:3.17.3-rc.831
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: copy files for build
        run: cp funding-service-design-frontend/json-forms/* runner/src/server/forms/ 
      - name: build new forms 
        run: yarn runner build
      