name: Deploy xforms to Gov PaaS

on:
  workflow_dispatch:
  push:
    # branches:
    # - master
    # - FS-389
    # - FS-390

    paths-ignore:
      - '**/README.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: Dev
    container: ghcr.io/xgovformbuilder/digital-form-builder-runner:latest
    steps:
      # - name: checkout code
      #   uses: actions/checkout@v2
      - name: debug
        run: |
          ls -ltr
          ls -ltr ..