name: Deploy xforms to Gov PaaS

on:
  workflow_dispatch:
  push:
    # branches:
    # - master
    # - FS-389
    # - FS-390

    paths-ignore:
      - '**/README.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: Dev
    services:
      runner:
        image: ghcr.io/xgovformbuilder/digital-form-builder-runner:3.17.3-rc.831
        ports:
           - 3009:3009
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - run: sleep 30
      - name: get from service runner
        run:  curl -i http://localhost:3009/test