name: Deploy xforms to Gov PaaS

on:
  workflow_dispatch:
  push:
    # branches:
    # - master
    # - FS-389
    # - FS-390

    paths-ignore:
      - '**/README.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Dev
    services:
      runner:
        image: ghcr.io/xgovformbuilder/digital-form-builder-runner:latest
        ports:
           - 3009:3009
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: frontend-runner:latest
          outputs: type=docker,dest=/tmp/frontend-runner-latest.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-runner
          path: /tmp/frontend-runner-latest.tar